CREATE TABLE "MEMBER_TYPE" (

"M_TYPE_CODE" NUMBER NOT NULL,

"M_TYPE_NAME" NVARCHAR2(100) NOT NULL

);

INSERT INTO "MEMBER_TYPE" VALUES(1, '일반사용자');

INSERT INTO "MEMBER_TYPE" VALUES(2, '단체사용자');

INSERT INTO "MEMBER_TYPE" VALUES(3, '관리자');

COMMIT;

		SELECT M_TYPE_CODE, M_TYPE_NAME
		FROM "MEMBER_TYPE"
		ORDER BY M_TYPE_CODE;
		
