--1) MEMBER_ID 컬럼에 PRIMARY KEY 제약조건 설정. -?완?-
--2) MEMBER_PWD 컬럼에 NOT NULL 제약조건 설정. -완-
--3) MEMBER_NAME 컬럼에 가변 길이 문자열 30byte 설정. -완-

CREATE TABLE MEMBERS(
		MEMBER_ID 		VARCHAR2(20),
		MEMBER_PWD 		VARCHAR2(20) NOT NULL,
		MEMBER_NAME 	VARCHAR2(30),
		MEMBER_AGE 		NUMBER,
		MEMBER_EMAIL 	VARCHAR2(50),
	  PRIMARY KEY(MEMBER_ID)
);

SELECT * FROM USER_CONSTRAINTS; -- 사용자 작성 제약조건 확인
SELECT * FROM USER_CONS_COLUMNS; -- 제약조건 걸린 컬럼 확인

DROP TABLE MEMBERS;


--1) BOARD_NO 컬럼에 PRIMARY KEY 제약조건 설정. -완-
--2) BOARD_WRITER 컬럼에 MEMERS 테이블의 MEMBER_ID를 참조하는 FOREIGN KEY 제약조건 설정.
--3) BOARD_REG_DATE(작성일) 컬럼에 현재 시간으로 기본값 설정 -완-

CREATE TABLE BOARDS(
		BOARD_NO 				NUMBER 					PRIMARY KEY,
		BOARD_TITLE 		VARCHAR2(100),
		BOARD_CONTENT 	VARCHAR2(4000),
		BOARD_REG_DATE 	DATE 						DEFAULT CURRENT_DATE,
		BOARD_WRITER 		VARCHAR2(20)
		CONSTRAINT BO_FK REFERENCES MEMBERS(MEMBER_ID)
);

DROP TABLE BOARDS;


원인
1. MEMBERS 테이블에  MEMBER_NAME 컬럼에 고정길이 문자열이 들어가 있다

2. BOARDS 테이블에 BOARD_REG_DATE 컬럼은 현재시간으로 기본값이 설정되어 있어야 하는데
	2023-03-22 의 날짜로 기본값이 설정되어 있다



조치내용
1. 요구사항 3번에 의거해 
	MEMBER_NAME CHAR(30) -> MEMBER_NAME VARCHAR2(30)으로 바꾸어준다.

2. 
BOARD_REG_DATE DATE DEFAULT '2023-03-22'
-> BOARD_REG_DATE DATE DEFAULT CURRENT_DATE 로 변경하여 현재시간이 기본값으로 설정되게 해준다.


