
COMMIT;

SELECT *
FROM FOLLOW;

SELECT 
	MEMBER_NO
FROM MEMBER
WHERE MEMBER_DEL_BAN_FL = 1;

SELECT *
FROM BOARD
/*WHERE MEMBER_NO = 2*/
WHERE BOARD_DEL_FL = 'Y'
ORDER BY MEMBER_NO ASC;

INSERT INTO FOLLOW
(FOLLOWING_MEMBER, FOLLOWER_MEMBER)
VALUES (18, 1);


SELECT
			ROW_NUMBER() OVER(ORDER BY BOARD_NO ASC) AS "RNUM",
			BOARD_NO,
			BOARD_CONTENT,
			MEMBER_NICKNAME,
			PROFILE_IMG,
			M.MEMBER_NO,
			
			(SELECT COUNT(*)
			 FROM	"COMMENT" C
			 WHERE	C.BOARD_NO = B.BOARD_NO
			 AND	C.COMMENT_DEL_FL = 'N') AS "COMMENT_COUNT",
			
			(SELECT COUNT(*)
			 FROM "BOARD_LIKE" L
			 WHERE L.BOARD_NO = B.BOARD_NO) AS "LIKE_COUNT",
			
			(SELECT COUNT(*)
			 FROM	"BOARD_LIKE" L2
			 WHERE	B.BOARD_NO = L2.BOARD_NO
			 AND	L2.MEMBER_NO = 18) AS "LIKE_CHECK",
			
			(SELECT COUNT(*)
			 FROM	"MARK" M2
			 WHERE	B.BOARD_NO = M2.BOARD_NO
			 AND	M2.MEMBER_NO = 18) AS "MARK_CHECK",
			
		
		CASE 
			WHEN CURRENT_DATE - B.CREATED_AT  < 1 / 24 / 60
			THEN FLOOR( (CURRENT_DATE - B.CREATED_AT) 
						* 24 * 60 * 60 ) || '초 전'
						
			WHEN CURRENT_DATE - B.CREATED_AT  < 1 / 24
			THEN FLOOR( (CURRENT_DATE - B.CREATED_AT) 
						* 24 * 60  ) || '분 전'
			
			WHEN CURRENT_DATE - B.CREATED_AT  < 1 
			THEN FLOOR( (CURRENT_DATE - B.CREATED_AT) 
						* 24 ) || '시간 전'
						
			ELSE TO_CHAR(B.CREATED_AT, 'YY-MM-DD')
						
		END AS "CREATED_AT"

			
		FROM
			"BOARD" B
		JOIN
			"MEMBER" M ON (B.MEMBER_NO = M.MEMBER_NO)
		JOIN
			"FOLLOW" F ON (B.MEMBER_NO = F.FOLLOWING_MEMBER)
		WHERE
			BOARD_DEL_FL = 'N'
		AND
			M.MEMBER_NO IN (
				SELECT
					FOLLOWER_MEMBER
				FROM
					FOLLOW
				WHERE
					FOLLOWING_MEMBER = 18
				AND
					CONFIRM = 1)
		ORDER BY
			RNUM DESC;
		
		
		
SELECT
	FOLLOWER_MEMBER
FROM
	FOLLOW
WHERE
	FOLLOWING_MEMBER = 18;

SELECT
    FOLLOWER_MEMBER
FROM
    FOLLOW
WHERE
    FOLLOWING_MEMBER = 18
AND
    FOLLOWER_MEMBER NOT IN (
        SELECT FOLLOWER_MEMBER
        FROM FOLLOW
        WHERE FOLLOWING_MEMBER = 18
    );

		
SELECT
	MEMBER_NO,
FROM
	"MEMBER" MM
JOIN
		"FOLLOW" FF ON
	(MM.MEMBER_NO = FF.FOLLOWING_MEMBER)
WHERE
		MEMBER_DEL_BAN_FL = 1
	AND
		MEMBER_NO != 18
	AND
		MM.MEMBER_NO NOT IN (
			SELECT
					FOLLOWER_MEMBER
			FROM
					FOLLOW
			WHERE
					FOLLOWING_MEMBER = 18
				AND
					CONFIRM = 1);
				
SELECT 
    MEMBER_NO
FROM 
    MEMBER
WHERE 
    MEMBER_DEL_BAN_FL = 1
AND 
    MEMBER_NO NOT IN (
        SELECT FOLLOWER_MEMBER
        FROM FOLLOW
        WHERE FOLLOWING_MEMBER = 18
    );

	SELECT 
	    MEMBER_NO,
	    MEMBER_NICKNAME,
	    MEMBER_NAME,
	    PROFILE_IMG
	FROM 
	    MEMBER MM
	WHERE 
	    MEMBER_DEL_BAN_FL = 1
	AND 
	    MEMBER_NO NOT IN (
	        SELECT FOLLOWER_MEMBER
	        FROM FOLLOW
	        WHERE FOLLOWING_MEMBER = 18);

SELECT
	*
FROM
	"COMMENT"
WHERE
	BOARD_NO = 3;
	


SELECT F.FOLLOWER_MEMBER, M.MEMBER_NICKNAME, M.PROFILE_IMG
FROM FOLLOW F
     JOIN MEMBER M ON(F.FOLLOWER_MEMBER = M.MEMBER_NO)
WHERE FOLLOWING_MEMBER =18 ;


/* 로그인한 회원이 팔로우한 24시간 내의 스토리(memberNo, memberNickname, profile_img) */
SELECT F.FOLLOWER_MEMBER, M.MEMBER_NICKNAME, M.PROFILE_IMG
FROM FOLLOW F
     JOIN MEMBER M ON(F.FOLLOWER_MEMBER = M.MEMBER_NO)
     JOIN STORY S ON(M.MEMBER_NO = S.MEMBER_NO)
WHERE FOLLOWING_MEMBER =18
AND S.STORY_DEL_FL = 'N'
AND S.CREATED_AT > CURRENT_DATE - 1;




SELECT CASE 
    WHEN COUNT(*) > 0 THEN 1 
    ELSE 0 
END
FROM STORY S
WHERE S.MEMBER_NO IN (
    SELECT F.FOLLOWING_NO 
    FROM FOLLOW F
    WHERE F.FOLLOWER_NO = 1)
AND S.STORY_DEL_FL = 'N'
AND S.CREATED_AT >= CURRENT_DATE - 1
AND NOT EXISTS (
    SELECT 1 
    FROM STORY_READ SR 
    WHERE SR.STORY_NO = S.STORY_NO 
    AND SR.MEMBER_NO = 18);
   
SELECT *
FROM STORY S
	JOIN MEMBER M ON (S.MEMBER_NO = M.MEMBER_NO)
WHERE S.MEMBER_NO = 1
AND S.STORY_DEL_FL = 'N';
	
	--AND  S.CREATED_AT > CURRENT_DATE - 1
	
	
	




SELECT
	COUNT(*)
FROM
	"STORY_READ"
WHERE
	MEMBER_NO = 18
AND
	STORY_NO = 20;


SELECT
	S.STORY_NO,
	M.MEMBER_NICKNAME,
	M.PROFILE_IMG
FROM
	STORY S
JOIN MEMBER M ON (S.MEMBER_NO = M.MEMBER_NO)
JOIN STORY_READ SR ON (S.STORY_NO = SR.STORY_NO)
WHERE
	S.STORY_DEL_FL = 'N'
AND
	S.CREATED_AT > CURRENT_DATE -1
AND
	M.MEMBER_NO IN (
		SELECT FOLLOWER_MEMBER
		FROM FOLLOW
		WHERE FOLLOWING_MEMBER = 18)
ORDER BY S.CREATED_AT DESC;




SELECT COUNT(*)
FROM STORY S1
JOIN MEMBER M1 ON (S1.MEMBER_NO = M1.MEMBER_NO)
WHERE S1.STORY_DEL_FL = 'N'
AND S1.CREATED_AT > CURRENT_DATE - 1
AND	M1.MEMBER_NO IN (
			SELECT FOLLOWER_MEMBER
			FROM FOLLOW
			WHERE FOLLOWING_MEMBER = 18);
		
SELECT S1.STORY_NO,
			 M1.MEMBER_NICKNAME,
			 M1.PROFILE_IMG
FROM STORY S1
JOIN MEMBER M1 ON (S1.MEMBER_NO = M1.MEMBER_NO)
WHERE S1.STORY_DEL_FL = 'N'
AND S1.CREATED_AT > CURRENT_DATE - 1
AND	M1.MEMBER_NO IN (
			SELECT FOLLOWER_MEMBER
			FROM FOLLOW
			WHERE FOLLOWING_MEMBER = 18)
ORDER BY S1.CREATED_AT DESC;



SELECT M1.MEMBER_NICKNAME,
       M1.PROFILE_IMG,
       LISTAGG(S1.STORY_NO, ', ') WITHIN GROUP (ORDER BY S1.CREATED_AT DESC) AS "STORY_NO"
FROM STORY S1
JOIN MEMBER M1 ON (S1.MEMBER_NO = M1.MEMBER_NO)
WHERE S1.STORY_DEL_FL = 'N'
  AND S1.CREATED_AT > CURRENT_DATE - 1
  AND M1.MEMBER_NO IN (
       SELECT FOLLOWER_MEMBER
       FROM FOLLOW
       WHERE FOLLOWING_MEMBER = 18
  )
GROUP BY M1.MEMBER_NICKNAME, M1.PROFILE_IMG
ORDER BY M1.MEMBER_NICKNAME;




	SELECT M1.MEMBER_NICKNAME,
	       M1.PROFILE_IMG
	FROM STORY S1
	JOIN MEMBER M1 ON (S1.MEMBER_NO = M1.MEMBER_NO)
	WHERE S1.STORY_DEL_FL = 'N'
	  AND S1.CREATED_AT > CURRENT_DATE - 1
	  AND M1.MEMBER_NO IN (
	       SELECT FOLLOWER_MEMBER
	       FROM FOLLOW
	       WHERE FOLLOWING_MEMBER = 18
	  )
	GROUP BY M1.MEMBER_NICKNAME, M1.PROFILE_IMG
	ORDER BY M1.MEMBER_NICKNAME;






SELECT S1.STORY_NO, S1.CREATED_AT, S1.MEMBER_NO
FROM STORY S1
JOIN MEMBER M1 ON (S1.MEMBER_NO = M1.MEMBER_NO)
WHERE S1.STORY_DEL_FL = 'N'
  AND S1.CREATED_AT > CURRENT_DATE - 1
  AND M1.MEMBER_NO IN (
       SELECT FOLLOWER_MEMBER
       FROM FOLLOW
       WHERE FOLLOWING_MEMBER = 18
  )
  AND S1.CREATED_AT = (
       SELECT MIN(S1_SUB.CREATED_AT)
       FROM STORY S1_SUB
       JOIN MEMBER M1_SUB ON (S1_SUB.MEMBER_NO = M1_SUB.MEMBER_NO)
       WHERE S1_SUB.STORY_DEL_FL = 'N'
         AND S1_SUB.CREATED_AT > CURRENT_DATE - 1
         AND M1_SUB.MEMBER_NO IN (
              SELECT FOLLOWER_MEMBER
              FROM FOLLOW
              WHERE FOLLOWING_MEMBER = 18
         )
  );



SELECT STORY_NO,
       MEMBER_NICKNAME,
       PROFILE_IMG
FROM (
    SELECT S1.STORY_NO,
           M1.MEMBER_NICKNAME,
           M1.PROFILE_IMG,
           S1.CREATED_AT,
           ROW_NUMBER() OVER (PARTITION BY M1.MEMBER_NICKNAME ORDER BY S1.CREATED_AT ASC) AS RN
    FROM STORY S1
    JOIN MEMBER M1 ON (S1.MEMBER_NO = M1.MEMBER_NO)
    WHERE S1.STORY_DEL_FL = 'N'
      AND S1.CREATED_AT > CURRENT_DATE - 1
      AND M1.MEMBER_NO IN (
           SELECT FOLLOWER_MEMBER
           FROM FOLLOW
           WHERE FOLLOWING_MEMBER = 18
      )
)
WHERE RN = 1
ORDER BY MEMBER_NICKNAME;



SELECT STORY_NO, MEMBER_NICKNAME, PROFILE_IMG
FROM (
    SELECT 
        S1.STORY_NO,
        M1.MEMBER_NICKNAME,
        M1.PROFILE_IMG,
        S1.CREATED_AT,
        ROW_NUMBER() OVER (PARTITION BY M1.MEMBER_NICKNAME ORDER BY S1.CREATED_AT ASC) AS RN
    FROM STORY S1
    JOIN MEMBER M1 ON S1.MEMBER_NO = M1.MEMBER_NO
    JOIN FOLLOW F ON F.FOLLOWER_MEMBER = M1.MEMBER_NO
    WHERE S1.STORY_DEL_FL = 'N'
      AND S1.CREATED_AT > SYSDATE - 1
      AND F.FOLLOWING_MEMBER = 18
)
WHERE RN = 1
ORDER BY MEMBER_NICKNAME;


-- STORY_COUNT > 0 : 안읽은 스토리가 존재
-- STORY_COUNT == 0 : 다 읽음
		SELECT 
		       MEMBER_NICKNAME,
		       PROFILE_IMG
		       ,COUNT(*) - SUM(STORY_CHECK) STORY_COUNT
		FROM (
		    SELECT S1.STORY_NO,
		           M1.MEMBER_NICKNAME,
		           M1.PROFILE_IMG,
		           S1.CREATED_AT
		           
	           	,(SELECT COUNT(*)
									FROM STORY_READ SR
									WHERE SR.MEMBER_NO = 18
									AND SR.STORY_NO = S1.STORY_NO
								) STORY_CHECK
		    FROM STORY S1
		    JOIN MEMBER M1 ON (S1.MEMBER_NO = M1.MEMBER_NO)
		    WHERE S1.STORY_DEL_FL = 'N'
		      AND S1.CREATED_AT > CURRENT_DATE - 1
		      AND M1.MEMBER_NO IN (
		           SELECT FOLLOWER_MEMBER
		           FROM FOLLOW
		           WHERE FOLLOWING_MEMBER = 18
		      )
		)
		GROUP BY  MEMBER_NICKNAME, PROFILE_IMG
		ORDER BY MEMBER_NICKNAME;

	
	SELECT * FROM STORY_READ;
	
	
INSERT INTO STORY_READ VALUES(18, 306, CURRENT_DATE);
COMMIT;


SELECT COUNT(S.STORY_NO)
FROM STORY S
JOIN MEMBER M ON (S.MEMBER_NO = M.MEMBER_NO)
WHERE STORY_DEL_FL ='N'
AND M.MEMBER_NICKNAME = 'glen'
AND S.CREATED_AT > CURRENT_DATE - 1;


SELECT S.STORY_NO
FROM STORY S
JOIN MEMBER M ON (S.MEMBER_NO = M.MEMBER_NO)
WHERE STORY_DEL_FL ='N'
AND M.MEMBER_NICKNAME = 'glen'
AND S.CREATED_AT > CURRENT_DATE - 1;


































	
	
	
	