
COMMIT;

SELECT *
FROM FOLLOW;

SELECT 
	MEMBER_NO
FROM MEMBER
WHERE MEMBER_DEL_BAN_FL = 1;

SELECT *
FROM BOARD
/*WHERE MEMBER_NO = 2*/
WHERE BOARD_DEL_FL = 'Y'
ORDER BY MEMBER_NO ASC;

INSERT INTO FOLLOW
(FOLLOWING_MEMBER, FOLLOWER_MEMBER)
VALUES (18, 1);


SELECT
			ROW_NUMBER() OVER(ORDER BY BOARD_NO ASC) AS "RNUM",
			BOARD_NO,
			BOARD_CONTENT,
			MEMBER_NICKNAME,
			PROFILE_IMG,
			M.MEMBER_NO,
			
			(SELECT COUNT(*)
			 FROM	"COMMENT" C
			 WHERE	C.BOARD_NO = B.BOARD_NO
			 AND	C.COMMENT_DEL_FL = 'N') AS "COMMENT_COUNT",
			
			(SELECT COUNT(*)
			 FROM "BOARD_LIKE" L
			 WHERE L.BOARD_NO = B.BOARD_NO) AS "LIKE_COUNT",
			
			(SELECT COUNT(*)
			 FROM	"BOARD_LIKE" L2
			 WHERE	B.BOARD_NO = L2.BOARD_NO
			 AND	L2.MEMBER_NO = 18) AS "LIKE_CHECK",
			
			(SELECT COUNT(*)
			 FROM	"MARK" M2
			 WHERE	B.BOARD_NO = M2.BOARD_NO
			 AND	M2.MEMBER_NO = 18) AS "MARK_CHECK",
			
		
		CASE 
			WHEN CURRENT_DATE - B.CREATED_AT  < 1 / 24 / 60
			THEN FLOOR( (CURRENT_DATE - B.CREATED_AT) 
						* 24 * 60 * 60 ) || '초 전'
						
			WHEN CURRENT_DATE - B.CREATED_AT  < 1 / 24
			THEN FLOOR( (CURRENT_DATE - B.CREATED_AT) 
						* 24 * 60  ) || '분 전'
			
			WHEN CURRENT_DATE - B.CREATED_AT  < 1 
			THEN FLOOR( (CURRENT_DATE - B.CREATED_AT) 
						* 24 ) || '시간 전'
						
			ELSE TO_CHAR(B.CREATED_AT, 'YY-MM-DD')
						
		END AS "CREATED_AT"

			
		FROM
			"BOARD" B
		JOIN
			"MEMBER" M ON (B.MEMBER_NO = M.MEMBER_NO)
		JOIN
			"FOLLOW" F ON (B.MEMBER_NO = F.FOLLOWING_MEMBER)
		WHERE
			BOARD_DEL_FL = 'N'
		AND
			M.MEMBER_NO IN (
				SELECT
					FOLLOWER_MEMBER
				FROM
					FOLLOW
				WHERE
					FOLLOWING_MEMBER = 18
				AND
					CONFIRM = 1)
		ORDER BY
			RNUM DESC;
		
		
		
SELECT
	FOLLOWER_MEMBER
FROM
	FOLLOW
WHERE
	FOLLOWING_MEMBER = 18;

SELECT
    FOLLOWER_MEMBER
FROM
    FOLLOW
WHERE
    FOLLOWING_MEMBER = 18
AND
    FOLLOWER_MEMBER NOT IN (
        SELECT FOLLOWER_MEMBER
        FROM FOLLOW
        WHERE FOLLOWING_MEMBER = 18
    );

		
SELECT
	MEMBER_NO,
FROM
	"MEMBER" MM
JOIN
		"FOLLOW" FF ON
	(MM.MEMBER_NO = FF.FOLLOWING_MEMBER)
WHERE
		MEMBER_DEL_BAN_FL = 1
	AND
		MEMBER_NO != 18
	AND
		MM.MEMBER_NO NOT IN (
			SELECT
					FOLLOWER_MEMBER
			FROM
					FOLLOW
			WHERE
					FOLLOWING_MEMBER = 18
				AND
					CONFIRM = 1);
				
SELECT 
    MEMBER_NO
FROM 
    MEMBER
WHERE 
    MEMBER_DEL_BAN_FL = 1
AND 
    MEMBER_NO NOT IN (
        SELECT FOLLOWER_MEMBER
        FROM FOLLOW
        WHERE FOLLOWING_MEMBER = 18
    );

	SELECT 
	    MEMBER_NO,
	    MEMBER_NICKNAME,
	    MEMBER_NAME,
	    PROFILE_IMG
	FROM 
	    MEMBER MM
	WHERE 
	    MEMBER_DEL_BAN_FL = 1
	AND 
	    MEMBER_NO NOT IN (
	        SELECT FOLLOWER_MEMBER
	        FROM FOLLOW
	        WHERE FOLLOWING_MEMBER = 18);


			
		
		
		