ALTER TABLE DAEMOIM.BOARD MODIFY BOARD_CONTENT VARCHAR2(4000) NULL;

SELECT "NEXT_IMG_NO";




CREATE OR REPLACE FUNCTION NEXT_BOARD_IMG_NO

-- 반환형
RETURN NUMBER

-- 사용할 변수
IS BOARD_IMG_NO NUMBER;

BEGIN 
	SELECT SEQ_BOARD_IMG_NO.NEXTVAL 
	INTO BOARD_IMG_NO
	FROM DUAL;

	RETURN BOARD_IMG_NO;
END;
;

COMMENT ON COLUMN DAEMOIM.REPORT.REPORT_LIST_NO IS '신고목록번호(SEQ_REPORT_NO)';

COMMIT;

UPDATE "MEMBER"
SET MEMBER_NICKNAME = '감성에세이'
WHERE MEMBER_NO = 25;
UPDATE "MEMBER"
SET MEMBER_EMAIL = 'emotionessay@goodle.com'
WHERE MEMBER_NO = 25;



SELECT LEVEL, C.*
  	FROM
  		(SELECT 
  			COMMENT_NO, COMMENT_CONTENT,
  			TO_CHAR(COMMENT_WRITE_DATE, 'YYYY"년" MM"월" DD"일" HH24"시" MI"분" SS"초"') COMMENT_WRITE_DATE,
  			BOARD_NO, MEMBER_NICKNAME, MEMBER_IMG, PARENT_COMMENT_NO, COMMENT_DEL_FL
  		FROM "COMMENT"
  		JOIN MEMBER USING(MEMBER_NO)
  		WHERE BOARD_NO = 4022) C
  	WHERE COMMENT_DEL_FL = 'N'
  	OR 0 != (SELECT COUNT(*) 
  			 FROM "COMMENT" SUB
  			 WHERE SUB.PARENT_COMMENT_NO = C.COMMENT_NO
  			 AND COMMENT_DEL_FL = 'N')
  	START WITH PARENT_COMMENT_NO IS NULL
  	CONNECT BY PRIOR COMMENT_NO = PARENT_COMMENT_NO
  	ORDER SIBLINGS BY COMMENT_NO;
  	
SELECT * FROM BOARD WHERE BOARD_TYPE_CODE =3 ORDER BY BOARD_NO DESC;
SELECT * FROM BOARD_IMG WHERE BOARD_NO = 4149;
SELECT * FROM BOARD_IMG ORDER BY BOARD_IMG_NO DESC;

SELECT BOARD_IMG_ORDER
FROM 
	BOARD_IMG
WHERE 
	BOARD_NO = 4149
ORDER BY 
	BOARD_IMG_ORDER ASC;



SELECT * FROM REPORT WHERE MEMBER_NO = 23;
  	