/* 관리자 계정(sys) 접속 후 수행*/
/*
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- 계정 생성
CREATE USER SPRING_LNS IDENTIFIED BY SPRING1234;

-- 권한 부여
GRANT CONNECT, RESOURCE TO SPRING_LNS;

-- 테이블 저장 공간 할당
ALTER USER SPRING_LNS
DEFAULT TABLESPACE USERS
QUOTA 100M ON USERS;
*/